image:
  tag: 9427d917
  repository: ghcr.io/mobot83/betamis/prediction-service
replicaCount: 2
ingress:
  enabled: true
  host: api.betamis.example.com # replace with real domain
  tls: true
  issuer: letsencrypt-prod
config:
  DB_HOST: ""
  KAFKA_BOOTSTRAP_SERVERS: ""
  KAFKA_SCHEMA_REGISTRY_URL: ""
  JWT_PUBLIC_KEY_LOCATION: ""
  JWT_ISSUER: ""
  OTEL_EXPORTER_OTLP_ENDPOINT: ""
secret:
  create: false
  existingSecret: betamis-prod-secrets
