quarkus.rest-client.football-data.url=https://api.football-data.org
football-data.api-token=${FOOTBALL_DATA_API_TOKEN}

# Comma-separated list of competition IDs to sync (e.g. PL = Premier League, FL1 = Ligue 1)
match.sync.competition-ids=PL, WC
# Cron expression for match sync (default: every 5 minutes)
match.sync.cron=0 */5 * * * ?

mp.messaging.outgoing.match-started.connector=smallrye-kafka
mp.messaging.outgoing.match-started.topic=match.started
mp.messaging.outgoing.match-started.value.serializer=io.quarkus.kafka.client.serialization.ObjectMapperSerializer

mp.messaging.outgoing.match-finished.connector=smallrye-kafka
mp.messaging.outgoing.match-finished.topic=match.finished
mp.messaging.outgoing.match-finished.value.serializer=io.quarkus.kafka.client.serialization.ObjectMapperSerializer
