image:
  tag: 4ff9538f
  repository: ghcr.io/mobot83/betamis/scoring-service
replicaCount: 2

ingress:
  enabled: true
  host: api.betamis.example.com   # replace with real domain
  tls: true
  issuer: letsencrypt-prod
config:
  DB_HOST: ""
  KAFKA_BOOTSTRAP_SERVERS: ""
  KAFKA_SCHEMA_REGISTRY_URL: ""
  REDIS_HOST: ""
  OTEL_EXPORTER_OTLP_ENDPOINT: ""
secret:
  create: false
  existingSecret: betamis-prod-secrets
